POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFhYWFhYWFhYSIsImlkIjoiNjJkYWJlNmU4M2Y2NTdiYTY1OWNjMjEyIiwiaWF0IjoxNjU4NTYzMjQ0fQ.rR4wYZdp04BQPiRxtfOy7pKk2jirJWvt2evVKfFPP2M

{
    "title": "Kokeiluotsikko",
    "author": "Kokeilukirjoittaja",
    "url": "kokeiluurli",
    "likes": 987,
    "user": "62dabe6e83f657ba659cc212"
}