POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Kokeiluotsikko",
    "author": "Kokeilukirjoittaja",
    "url": "kokeiluurli",
    "likes": 99999,
    "user": "62dabe6e83f657ba659cc212"
}