POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imphc2thIiwiaWQiOiI2MmRiZjlkOThkZDk2NjExZDc3NThiOWQiLCJpYXQiOjE2NTg1ODM1NDJ9.Uij5C0KdsHFF2NPeieWAk3M7STsne74sEmCN83EVuko

{
    "title": "Jaska Title",
    "author": "Jaska Jaskanen",
    "url": "jaskaurli",
    "likes": 6969,
    "user": "62dbf9d98dd96611d7758b9d"
}